=== leopm99/mobiuz/dist/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" type="npcType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="npcType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="acquire" type="acquireType" minOccurs="0" maxOccurs="1" />
			<xs:element name="ai" type="aiType" minOccurs="0" maxOccurs="1" />
			<xs:element name="collision" type="collisionType" minOccurs="0" maxOccurs="1" />
			<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
			<xs:element name="dropLists" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="drop" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute type="xs:int" name="id" use="required"/>
													<xs:attribute type="xs:long" name="min" use="required"/>
													<xs:attribute type="xs:long" name="max" use="required"/>
													<xs:attribute type="xs:double" name="chance" use="required"/>
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
									<xs:element name="group" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute type="xs:int" name="id" use="required"/>
																<xs:attribute type="xs:long" name="min" use="required"/>
																<xs:attribute type="xs:long" name="max" use="required"/>
																<xs:attribute type="xs:double" name="chance" use="required"/>
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute type="xs:double" name="chance" use="optional"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="spoil" minOccurs="0">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute type="xs:int" name="id" use="optional"/>
													<xs:attribute type="xs:long" name="min" use="optional"/>
													<xs:attribute type="xs:long" name="max" use="optional"/>
													<xs:attribute type="xs:double" name="chance" use="optional"/>
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="equipment" type="equipmentType" minOccurs="0" maxOccurs="1" />
			<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="parameters" type="parametersType" minOccurs="0" maxOccurs="1" />
			<xs:element name="race" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
			<xs:element name="sex" type="xs:token" minOccurs="0" maxOccurs="1" />
			<xs:element name="shots" type="shotsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="skillList" type="skillType" minOccurs="0" maxOccurs="1" />
			<xs:element name="stats" type="statsType" minOccurs="0" maxOccurs="1" />
			<xs:element name="status" type="statusType" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="displayId" type="xs:positiveInteger" />
		<xs:attribute name="level" type="xs:byte" />
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="usingServerSideName" type="xs:boolean" />
		<xs:attribute name="title" type="xs:string" />
		<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="acquireType">
		<xs:attribute name="exp" type="xs:decimal" />
		<xs:attribute name="sp" type="xs:decimal" />
		<xs:attribute name="raidPoints" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="aiType">
		<xs:all>
			<xs:element name="skill" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
					<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="clanList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="unbounded">
						<xs:element name="clan" type="xs:token" />
						<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="type" type="xs:token" />
		<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
		<xs:attribute name="isChaos" type="xs:boolean" />
		<xs:attribute name="isAggressive" type="xs:boolean" />
	</xs:complexType>
	
	<xs:complexType name="collisionType">
		<xs:all>
			<xs:element name="radius" type="size" minOccurs="0" maxOccurs="1" />
			<xs:element name="height" type="size" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="size">
		<xs:attribute name="normal" type="xs:decimal" />
		<xs:attribute name="grown" type="xs:decimal" />
	</xs:complexType>
	
		<xs:complexType name="dropListsType">
		<xs:all>
			<xs:element name="drop" type="dropList" minOccurs="0" maxOccurs="1" />
			<xs:element name="spoil" type="dropList" minOccurs="0" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	
	<xs:complexType name="dropList">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="item" type="dropListItem" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="dropListItem">
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
		<xs:attribute name="min" type="xs:nonNegativeInteger" />
		<xs:attribute name="max" type="xs:positiveInteger" />
		<xs:attribute name="chance" type="xs:decimal" />
	</xs:complexType>
	
	<xs:complexType name="equipmentType">
		<xs:attribute name="chest" type="xs:nonNegativeInteger" />
		<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
		<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="parametersType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="param">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="skill">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					<xs:attribute name="level" type="xs:positiveInteger" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="minions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								<xs:attribute name="count" type="xs:positiveInteger" use="required" />
								<xs:attribute name="max" type="xs:positiveInteger" use="optional" />
								<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
								<xs:attribute name="weightPoint" type="xs:integer" use="optional" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:token" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="shotsType">
		<xs:attribute name="soul" type="xs:nonNegativeInteger" />
		<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
		<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
		<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
	</xs:complexType>

	<xs:complexType name="skillType">
		<xs:sequence>
			<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
					<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="statsType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="vitals" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="hp" type="xs:decimal" />
					<xs:attribute name="hpRegen" type="xs:decimal" />
					<xs:attribute name="mp" type="xs:decimal" />
					<xs:attribute name="mpRegen" type="xs:decimal" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attack" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="random" type="xs:nonNegativeInteger" />
					<xs:attribute name="critical" type="xs:nonNegativeInteger" />
					<xs:attribute name="accuracy" type="xs:decimal" />
					<xs:attribute name="attackSpeed" type="xs:nonNegativeInteger" />
					<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
					<xs:attribute name="type">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="SWORD" />
								<xs:enumeration value="BLUNT" />
								<xs:enumeration value="DAGGER" />
								<xs:enumeration value="BOW" />
								<xs:enumeration value="DUAL" />
								<xs:enumeration value="POLE" />
								<xs:enumeration value="DUALFIST" />
								<xs:enumeration value="FIST" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="range" type="xs:nonNegativeInteger" />
					<xs:attribute name="distance" type="xs:nonNegativeInteger" />
					<xs:attribute name="width" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="defence" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="physical" type="xs:decimal" />
					<xs:attribute name="magical" type="xs:decimal" />
					<xs:attribute name="evasion" type="xs:integer" />
					<xs:attribute name="shield" type="xs:nonNegativeInteger" />
					<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
				</xs:complexType>
			</xs:element>
			<xs:element name="attribute" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="attack" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="FIRE" />
											<xs:enumeration value="WATER" />
											<xs:enumeration value="WIND" />
											<xs:enumeration value="EARTH" />
											<xs:enumeration value="DARK" />
											<xs:enumeration value="HOLY" />
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="value" type="xs:nonNegativeInteger" />
							</xs:complexType>
						</xs:element>
						<xs:element name="defence" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="fire" type="xs:integer" />
								<xs:attribute name="water" type="xs:integer" />
								<xs:attribute name="wind" type="xs:integer" />
								<xs:attribute name="earth" type="xs:integer" />
								<xs:attribute name="holy" type="xs:integer" />
								<xs:attribute name="dark" type="xs:integer" />
								<xs:attribute name="default" type="xs:integer" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="speed" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="walk" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
						<xs:element name="run" minOccurs="0" maxOccurs="1">
							<xs:complexType>
								<xs:attribute name="ground" type="xs:decimal" />
								<xs:attribute name="swim" type="xs:decimal" />
								<xs:attribute name="fly" type="xs:decimal" />
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
		</xs:choice>
		<xs:attribute name="str" type="xs:nonNegativeInteger" />
		<xs:attribute name="int" type="xs:nonNegativeInteger" />
		<xs:attribute name="dex" type="xs:nonNegativeInteger" />
		<xs:attribute name="wit" type="xs:nonNegativeInteger" />
		<xs:attribute name="con" type="xs:nonNegativeInteger" />
		<xs:attribute name="men" type="xs:nonNegativeInteger" />
	</xs:complexType>
	
	<xs:complexType name="statusType">
		<xs:attribute name="unique" type="xs:boolean" />
		<xs:attribute name="attackable" type="xs:boolean" />
		<xs:attribute name="talkable" type="xs:boolean" />
		<xs:attribute name="targetable" type="xs:boolean" />
		<xs:attribute name="undying" type="xs:boolean" />
		<xs:attribute name="showName" type="xs:boolean" />
		<xs:attribute name="randomWalk" type="xs:boolean" />
		<xs:attribute name="randomAnimation" type="xs:boolean" />
		<xs:attribute name="flying" type="xs:boolean" />
		<xs:attribute name="canMove" type="xs:boolean" />
		<xs:attribute name="noSleepMode" type="xs:boolean" />
		<xs:attribute name="passableDoor" type="xs:boolean" />
		<xs:attribute name="hasSummoner" type="xs:boolean" />
		<xs:attribute name="canBeSown" type="xs:boolean" />
	</xs:complexType>
	
</xs:schema>

=== leopm99/mobiuz/dist/game/data/stats/npcs/custom/custom_l2journey.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/npcs.xsd">
	<npc id="36603" displayId="13155" name="Seller" usingServerSideName="true" title="Gm Shop" usingServerSideTitle="true" type="Merchant">
		<collision>
			<radius normal="8" />
			<height normal="30" />
		</collision>
	</npc>
	<!-- Delevel Manager -->
	<npc id="36604" displayId="32534" name="Ammit" usingServerSideName="true" title="Experience Devourer" usingServerSideTitle="true" type="Folk">
		<collision>
			<radius normal="19" />
			<height normal="44" />
		</collision>
	</npc>
	<!-- Nobless Manager -->
	<npc id="36605" displayId="32138" name="Thranduil" usingServerSideName="true" title="Noblesse Master" usingServerSideTitle="true" type="Folk">
		<collision>
			<radius normal="18" />
			<height normal="28" />
		</collision>
	</npc>
	<!-- Achievement NPC -->
	<npc id="70000" displayId="31275" name="Drika" usingServerSideName="true" title="Achievement Master" usingServerSideTitle="true" type="Folk">
		<collision>
			<radius normal="8" />
			<height normal="30" />
		</collision>
	</npc>
	<!-- Collection NPC -->
	<npc id="70001" displayId="32744" name="Lorenzo" usingServerSideName="true" title="Collectible Archives" usingServerSideTitle="true" type="Folk">
		<collision>
			<radius normal="8" />
			<height normal="23" />
		</collision>
	</npc>
	<!-- Hidden Treasure Chest - spawned invisible by ai/others/HiddenTreasureChest, revealed only to players -->
	<!-- affected by the "Treasure Hunter Search" buff (skill 20000), or to everyone once attacked. -->
	<!-- Stats/drops reused from the regular "Treasure Chest" (id 18265). -->
	<npc id="70002" displayId="18265" level="21" name="Hidden Treasure Chest" usingServerSideName="true" type="Chest">
		<race>CONSTRUCT</race>
		<sex>MALE</sex>
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="376.063268689487" hpRegen="1.5" mp="205.2" mpRegen="1.5" />
			<attack physical="47.919244061454" magical="32.7226319401133" random="30" critical="4" accuracy="4.75" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="92.6271011629928" magical="56.1115632895055" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="80" />
				<run ground="1" />
			</speed>
			<hitTime>560</hitTime>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="1" /> <!-- HP Increase (1x) -->
			<skill id="4409" level="1" /> <!-- MP Increase (1x) -->
			<skill id="4410" level="11" /> <!-- Average P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="21" /> <!-- Extremely Strong M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4416" level="2" /> <!-- Magic Creatures -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<dropLists>
			<drop>
				<item id="736" min="4" max="8" chance="90.91" /> <!-- Scroll of Escape -->
				<item id="737" min="1" max="3" chance="90.91" /> <!-- Scroll of Resurrection -->
				<item id="10262" min="1" max="1" chance="40" /> <!-- Critical Hit Juice -->
				<item id="10265" min="1" max="1" chance="40" /> <!-- Evasion Juice -->
				<item id="10260" min="1" max="1" chance="38.1" /> <!-- Alacrity Juice -->
				<item id="10264" min="1" max="1" chance="32.88" /> <!-- Casting Spd. Juice -->
				<item id="10269" min="1" max="1" chance="33.72" /> <!-- Defense Juice -->
				<item id="10268" min="1" max="1" chance="33.72" /> <!-- Speed Juice -->
				<item id="10261" min="1" max="1" chance="29.52" /> <!-- Accuracy Juice -->
				<item id="10267" min="1" max="1" chance="30.23" /> <!-- Power Juice -->
				<item id="10266" min="1" max="1" chance="28.57" /> <!-- M. Atk. Juice -->
				<item id="10263" min="1" max="1" chance="31.4" /> <!-- Critical Rate Juice -->
				<item id="5593" min="1" max="1" chance="75.55" /> <!-- SP Scroll (Low-Grade) -->
				<item id="5594" min="1" max="1" chance="63.55" /> <!-- SP Scroll (Medium-Grade) -->
				<item id="955" min="1" max="1" chance="0.63" /> <!-- Scroll: Enchant Weapon (D-Grade) -->
				<item id="956" min="1" max="1" chance="5.51" /> <!-- Scroll: Enchant Armor (D-Grade) -->
				<item id="10133" min="1" max="1" chance="22" /> <!-- Transformation Scroll: Grail Apostle -->
				<item id="20364" min="1" max="1" chance="22" /> <!-- Transformation Scroll: Omen Beast -->
				<item id="10132" min="1" max="1" chance="22" /> <!-- Transformation Scroll: Death Blader -->
			</drop>
		</dropLists>
		<collision>
			<radius normal="8.5" />
			<height normal="8.5" />
		</collision>
	</npc>
</list>

=== leopm99/mobiuz/dist/game/data/stats/npcs/custom/ketra_varka_war.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/npcs.xsd">
	<npc id="40000" displayId="21339" level="85" type="Folk" usingServerSideName="true" name="Ketra Orc" usingServerSideTitle="true" title="General">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="6719" /> <!-- rhand: Monster Only(Ketra Orc Chieftain) -->
		<acquire exp="20988" sp="2469" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="3077.1572058" hpRegen="8.874" mp="1848.24" mpRegen="3.1314" />
			<attack physical="1009.3950039" magical="719.599557852" random="50" critical="1" accuracy="15" attackSpeed="253" type="BLUNT" range="40" distance="80" width="120" />
			<defence physical="373.969485" magical="261.022284" evasion="2" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="24" />
				<run ground="175" />
			</speed>
			<hitTime>510</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="50" spiritChance="50" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai aggroRange="300" clanHelpRange="300">
			<clanList>
				<clan>KETRA_ORC</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="17" />
			<height normal="46.2" />
		</collision>
	</npc>
	<npc id="40001" displayId="21343" level="85" type="Monster" usingServerSideName="true" name="Ketra Orc" usingServerSideTitle="true" title="Commander">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="80" lhand="6919" /> <!-- rhand: Tallum Blade lhand: Monster Only (Shield of Ketra Orc) -->
		<acquire exp="32800" sp="3725" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2975.2369188" hpRegen="8.721" mp="1742.976" mpRegen="3.0804" />
			<attack physical="938.20801458" magical="656.66638089" random="10" critical="8" accuracy="3" attackSpeed="253" type="DAGGER" range="40" distance="80" width="120" />
			<defence physical="354.8183475" magical="239.180922" evasion="3" shield="173" shieldRate="20" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="27" />
				<run ground="175" />
			</speed>
			<hitTime>480</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="50" spiritChance="50" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai type="BALANCED" aggroRange="300" clanHelpRange="300" isAggressive="false">
			<clanList>
				<clan>KETRA_ORC</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="15" />
			<height normal="36" />
		</collision>
	</npc>
	<npc id="40002" displayId="21331" level="85" type="Monster" usingServerSideName="true" name="Ketra Orc" usingServerSideTitle="true" title="Warrior">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="79" lhand="6919" /> <!-- rhand: Sword of Damascus lhand: Monster Only (Shield of Ketra Orc) -->
		<acquire exp="18608" sp="2089" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2937.9838056" hpRegen="8.67" mp="1708.296" mpRegen="3.06" />
			<attack physical="912.6537108" magical="635.688655236" random="30" critical="4" accuracy="6.75" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="348.2025" magical="231.837152158566" evasion="2" shield="171" shieldRate="20" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="36" />
				<run ground="175" />
			</speed>
			<hitTime>540</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="30" spiritChance="30" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai aggroRange="300" clanHelpRange="300" isAggressive="false">
			<clanList>
				<clan>KETRA_ORC</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="12" grown="14" />
			<height normal="24" grown="28.8" />
		</collision>
	</npc>
	<npc id="40003" displayId="21366" level="85" type="Folk" usingServerSideName="true" name="Varka Silenos" usingServerSideTitle="true" title="General">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="2500" /> <!-- rhand: Dark Legion's Edge -->
		<acquire exp="27045" sp="2858" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2974.35686398316" hpRegen="8.5" mp="1607.4" mpRegen="3" />
			<attack physical="890.50085998804" magical="608.096657928153" random="50" critical="1" accuracy="9" attackSpeed="253" type="BLUNT" range="40" distance="80" width="120" />
			<defence physical="332.70061" magical="243.45587" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="25" />
				<run ground="175" />
			</speed>
			<hitTime>480</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="60" spiritChance="60" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai aggroRange="300" clanHelpRange="300">
			<clanList>
				<clan>VARKA_SILENOS</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="18" />
			<height normal="42.5" />
		</collision>
	</npc>
	<npc id="40004" displayId="21362" level="78" type="Monster" usingServerSideName="true" name="Varka Silenos" usingServerSideTitle="true" title="Commander">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="2504" /> <!-- rhand: Meteor Shower -->
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2974.35686398316" hpRegen="8.5" mp="1607.4" mpRegen="3" />
			<attack physical="890.50085998804" magical="608.096657928153" random="50" critical="1" accuracy="9" attackSpeed="253" type="BLUNT" range="40" distance="80" width="120" />
			<defence physical="332.70061" magical="243.45587" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="25" />
				<run ground="175" />
			</speed>
			<hitTime>480</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="50" spiritChance="50" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai aggroRange="300" clanHelpRange="300" isAggressive="false">
			<clanList>
				<clan>VARKA_SILENOS</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="18" />
			<height normal="42.5" />
		</collision>
	</npc>
	<npc id="40005" displayId="21358" level="78" type="Monster" usingServerSideName="true" name="Varka Silenos" usingServerSideTitle="true" title="Warrior">
		<race>HUMANOID</race>
		<sex>MALE</sex>
		<equipment rhand="142" lhand="6918" /> <!-- rhand: Keshanberk lhand: Monster Only (Shield of Silenos) -->
		<acquire exp="25564" sp="2696" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2974.35686398316" hpRegen="8.5" mp="1607.4" mpRegen="3" />
			<attack physical="890.50085998804" magical="608.096657928153" random="30" critical="4" accuracy="4.75" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="332.70061" magical="243.45587" shield="171" shieldRate="20" />
			<attribute>
				<defence fire="20" water="20" wind="20" earth="20" holy="20" dark="20" />
			</attribute>
			<speed>
				<walk ground="34" />
				<run ground="175" />
			</speed>
			<hitTime>480</hitTime>
		</stats>
		<status undying="false" canBeSown="true" />
		<shots shotChance="50" spiritChance="50" />
		<exCrtEffect>false</exCrtEffect>
		<sNpcPropHpRate>2</sNpcPropHpRate>
		<ai type="BALANCED" aggroRange="300" clanHelpRange="300" isAggressive="false">
			<clanList>
				<clan>VARKA_SILENOS</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="16" />
			<height normal="41" />
		</collision>
	</npc>	
</list>
