=== leopm99/mobiuz/dist/game/data/xsd/spawns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="AIData" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											<xs:attribute name="x" type="xs:integer" use="optional" />
											<xs:attribute name="y" type="xs:integer" use="optional" />
											<xs:attribute name="z" type="xs:integer" use="optional" />
											<xs:attribute name="heading" type="xs:integer" use="optional" />
											<xs:attribute name="count" type="xs:positiveInteger" use="optional" />
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="chaseRange" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="randomWalkRange" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="periodOfDay" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day" />
														<xs:enumeration value="night" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" use="optional" />
						<xs:attribute type="xs:string" name="zone" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
	</xs:complexType>
	</xs:element>
</xs:schema>

=== leopm99/mobiuz/dist/game/data/spawns/Others/17_25.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="17_25">
		<npc id="4327" x="-92545" y="244590" z="-3547" heading="12868" /> <!-- Worshipper -->
		<npc id="4328" x="-92657" y="244716" z="-3547" heading="48184" /> <!-- Altar Guard -->
		<npc id="4328" x="-92383" y="244642" z="-3547" heading="5431" /> <!-- Altar Guard -->
		<npc id="20545" x="-87140" y="251482" z="-3608" heading="62051" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-86529" y="251952" z="-3624" heading="37512" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-84860" y="251242" z="-3592" heading="23095" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-76457" y="254228" z="-3208" heading="52895" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-75504" y="252167" z="-3328" heading="13878" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-74866" y="255282" z="-3216" heading="3550" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-74412" y="253200" z="-3328" heading="41180" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-74250" y="256558" z="-3120" heading="2192" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-74019" y="256725" z="-3120" heading="63612" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-73363" y="253876" z="-3328" heading="21407" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-73186" y="254866" z="-3280" heading="40305" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-72971" y="255123" z="-3256" heading="22286" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="20545" x="-71081" y="254981" z="-3232" heading="48948" respawnDelay="25" /> <!-- Young Keltir -->
		<npc id="27003" x="-96984" y="247644" z="-3640" heading="20794" respawnDelay="180" /> <!-- Spirit Of Mirrors -->
		<npc id="30001" x="-86385" y="243267" z="-3717" heading="52000" respawnDelay="60" /> <!-- Lector -->
		<npc id="30002" x="-86733" y="242918" z="-3720" heading="61440" respawnDelay="60" /> <!-- Jackson -->
		<npc id="30003" x="-83789" y="240799" z="-3717" heading="32768" respawnDelay="60" /> <!-- Silvia -->
		<npc id="30004" x="-84204" y="240403" z="-3720" heading="14000" respawnDelay="60" /> <!-- Katerina -->
		<npc id="30005" x="-81512" y="243424" z="-3712" heading="38000" respawnDelay="60" /> <!-- Wilford -->
		<npc id="30006" x="-84108" y="244604" z="-3728" heading="40960" respawnDelay="60" /> <!-- Roxxy -->
		<npc id="30008" x="-71384" y="258304" z="-3104" heading="42000" respawnDelay="60" /> <!-- Roien -->
		<npc id="30009" x="-71424" y="258336" z="-3104" heading="42000" respawnDelay="60" /> <!-- Newbie Helper -->
		<npc id="30017" x="-91008" y="248016" z="-3560" heading="6000" respawnDelay="60" /> <!-- Gallint -->
		<npc id="30019" x="-91036" y="248044" z="-3560" heading="6000" respawnDelay="60" /> <!-- Newbie Helper -->
		<npc id="30026" x="-83326" y="242964" z="-3720" heading="55344" respawnDelay="60" /> <!-- Bitz -->
		<npc id="30027" x="-83020" y="242553" z="-3720" heading="11200" respawnDelay="60" /> <!-- Gwinter -->
		<npc id="30028" x="-82809" y="242751" z="-3720" heading="36864" respawnDelay="60" /> <!-- Pintage -->
		<npc id="30029" x="-83175" y="243065" z="-3720" heading="45956" respawnDelay="60" /> <!-- Minia -->
		<npc id="30031" x="-84516" y="245449" z="-3712" heading="40960" respawnDelay="60" /> <!-- Biotin -->
		<npc id="30032" x="-84981" y="244764" z="-3720" heading="24576" respawnDelay="60" /> <!-- Yohanes -->
		<npc id="30033" x="-84729" y="245001" z="-3720" heading="24576" respawnDelay="60" /> <!-- Baulro -->
		<npc id="30035" x="-84965" y="245222" z="-3720" heading="57000" respawnDelay="60" /> <!-- Harrys -->
		<npc id="30036" x="-85186" y="245001" z="-3720" heading="57000" respawnDelay="60" /> <!-- Petron -->
		<npc id="30039" x="-82236" y="241573" z="-3728" heading="58500" respawnDelay="60" /> <!-- Gilbert -->
		<npc id="30040" x="-82515" y="241221" z="-3728" heading="58500" respawnDelay="60" /> <!-- Leon -->
		<npc id="30041" x="-82319" y="244709" z="-3728" heading="9000" respawnDelay="60" /> <!-- Arnold -->
		<npc id="30042" x="-82659" y="244992" z="-3712" heading="9000" respawnDelay="60" /> <!-- Abellos -->
		<npc id="30043" x="-86114" y="244682" z="-3728" heading="25500" respawnDelay="60" /> <!-- Johnstone -->
		<npc id="30044" x="-86328" y="244448" z="-3720" heading="25500" respawnDelay="60" /> <!-- Chiperan -->
		<npc id="30045" x="-86322" y="241215" z="-3728" heading="42500" respawnDelay="60" /> <!-- Kenyos -->
		<npc id="30046" x="-85964" y="240947" z="-3728" heading="42500" respawnDelay="60" /> <!-- Hanks -->
		<npc id="30047" x="-97131" y="258946" z="-3616" heading="0" respawnDelay="60" /> <!-- Firon -->
		<npc id="30048" x="-84436" y="242793" z="-3728" heading="42000" respawnDelay="60" /> <!-- Darin -->
		<npc id="30049" x="-83163" y="243560" z="-3728" heading="20480" respawnDelay="60" /> <!-- Bonnie -->
		<npc id="30050" x="-84057" y="242832" z="-3728" heading="59000" respawnDelay="60" /> <!-- Elias -->
		<npc id="30051" x="-82041" y="242718" z="-3720" heading="20480" respawnDelay="60" /> <!-- Cristel -->
		<npc id="30054" x="-81895" y="243917" z="-3712" heading="41500" respawnDelay="60" /> <!-- Rant -->
		<npc id="30055" x="-81840" y="243534" z="-3712" heading="5000" respawnDelay="60" /> <!-- Rolfe -->
		<npc id="30283" x="-85026" y="242689" z="-3720" heading="57344" respawnDelay="60" /> <!-- Altran -->
		<npc id="30312" x="-78939" y="240305" z="-3440" heading="28672" respawnDelay="60" /> <!-- Rockswell -->
		<npc id="30368" x="-85301" y="244587" z="-3720" heading="24576" respawnDelay="60" /> <!-- Lilith -->
		<npc id="30406" x="-92622" y="254108" z="-3304" heading="0" respawnDelay="60" /> <!-- Matheo -->
		<npc id="30598" x="-84081" y="243227" z="-3728" heading="9000" respawnDelay="60" /> <!-- Newbie Guide -->
		<npc id="30733" x="-97211" y="258230" z="-3544" heading="57343" respawnDelay="60" /> <!-- Guard -->
		<npc id="30733" x="-87847" y="250564" z="-3608" heading="4096" respawnDelay="60" /> <!-- Guard -->
		<npc id="30733" x="-87406" y="250079" z="-3592" heading="8192" respawnDelay="60" /> <!-- Guard -->
		<npc id="30990" x="-84143" y="244637" z="-3728" heading="41000" respawnDelay="60" /> <!-- Lottery Ticket Seller -->
		<npc id="31031" x="-82795" y="243147" z="-3718" heading="16384" respawnDelay="5" /> <!-- Broadcasting Tower -->
		<npc id="31032" x="-97475" y="231246" z="-3608" heading="14380" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-96710" y="257075" z="-3520" heading="37435" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-95034" y="234451" z="-3688" heading="15432" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-94533" y="257153" z="-3312" heading="33909" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-87718" y="238995" z="-3608" heading="8594" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-87346" y="254668" z="-3720" heading="25594" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-86666" y="237396" z="-3696" heading="54603" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-82901" y="253704" z="-3728" heading="18004" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-82045" y="239424" z="-3688" heading="53735" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-75001" y="255290" z="-3208" heading="20103" respawnDelay="60" /> <!-- Guard -->
		<npc id="31356" x="-81920" y="243892" z="-3714" heading="7000" respawnDelay="60" /> <!-- Remy -->
		<npc id="31357" x="-82428" y="245203" z="-3712" heading="0" respawnDelay="60" /> <!-- Leandro -->
		<npc id="31413" x="-85312" y="244752" z="-3725" heading="8000" respawnDelay="60" /> <!-- Antonio -->
		<npc id="31562" x="-83904" y="240576" z="-3712" heading="25000" respawnDelay="60" /> <!-- Klufe -->
		<npc id="31688" x="-85151" y="241476" z="-3728" heading="25000" respawnDelay="60" /> <!-- Grand Olympiad Manager -->
		<npc id="31690" x="-85096" y="241516" z="-3728" heading="25000" respawnDelay="60" /> <!-- Monument of Heroes -->
		<npc id="31775" x="-83472" y="242896" z="-3728" heading="39000" respawnDelay="60" /> <!-- Adventure Guildsman -->
		<npc id="31776" x="-86080" y="241488" z="-3728" heading="57000" respawnDelay="60" /> <!-- Adventure Guildsman -->
		<npc id="32478" x="-81920" y="243360" z="-3728" heading="40000" respawnDelay="60" /> <!-- Dimensional Merchant -->
		<npc id="35103" x="-83536" y="243280" z="-3728" heading="24400" respawnDelay="60" /> <!-- Manor Manager -->
		<npc id="30733" x="-78053" y="250443" z="-3549" heading="42893" respawnDelay="60" randomWalkRange="200" /> <!-- Guard -->
		<npc id="31032" x="-82518" y="246149" z="-3683" heading="24696" respawnDelay="60" /> <!-- Guard -->
		<npc id="31032" x="-81313" y="245044" z="-3727" heading="6172" respawnDelay="60" /> <!-- Guard -->
	</spawn>
</list>

=== leopm99/mobiuz/dist/game/data/spawns/Aden/ForsakenPlains.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn zone="forsakenPlains">
		<npc id="21021" x="170447" y="41196" z="-4891" heading="20512" respawnDelay="27" /> <!-- Sharp Talon Tiger -->
		<npc id="20649" x="173332" y="44154" z="-4919" heading="63607" respawnDelay="60" /> <!-- Hamrut -->
		<npc id="20650" x="175069" y="43763" z="-4847" heading="64519" respawnDelay="60" /> <!-- Kranrot -->
		<npc id="21022" x="172801" y="41467" z="-4978" heading="58554" respawnDelay="27" /> <!-- Fallen Orc Captain -->
		<npc id="21020" x="170723" y="41149" z="-4896" heading="51498" respawnDelay="27" /> <!-- Fallen Orc Shaman -->
		<npc id="21020" x="170274" y="41439" z="-4900" heading="26786" respawnDelay="27" /> <!-- Fallen Orc Shaman -->
		<npc id="21021" x="169216" y="41843" z="-4904" heading="35621" respawnDelay="27" /> <!-- Sharp Talon Tiger -->
		<npc id="20679" x="169120" y="43742" z="-4848" heading="21766" respawnDelay="27" /> <!-- Marsh Stalker -->
		<npc id="21021" x="173106" y="43026" z="-4968" heading="16563" respawnDelay="27" /> <!-- Sharp Talon Tiger -->
		<npc id="20680" x="172552" y="43892" z="-4959" heading="22159" respawnDelay="27" /> <!-- Marsh Drake -->
		<npc id="21020" x="171781" y="42991" z="-4984" heading="57445" respawnDelay="27" /> <!-- Fallen Orc Shaman -->
		<npc id="20650" x="171321" y="43305" z="-4910" heading="21220" respawnDelay="60" /> <!-- Kranrot -->
		<npc id="21022" x="178061" y="41118" z="-3698" heading="18684" respawnDelay="27" /> <!-- Fallen Orc Captain -->
		<npc id="21021" x="177737" y="41067" z="-3729" heading="34396" respawnDelay="27" /> <!-- Sharp Talon Tiger -->
		<npc id="21020" x="178993" y="41942" z="-3784" heading="1982" respawnDelay="27" /> <!-- Fallen Orc Shaman -->
		<npc id="21021" x="181698" y="41497" z="-3696" heading="19632" respawnDelay="27" /> <!-- Sharp Talon Tiger -->
		<npc id="21018" x="179646" y="40648" z="-3753" heading="37449" respawnDelay="27" /> <!-- Ancient Gargoyle -->
		<npc id="21019" x="180577" y="37465" z="-4824" heading="21496" respawnDelay="27" /> <!-- Fallen Orc Archer -->
		<npc id="21018" x="170112" y="37573" z="-4280" heading="10881" respawnDelay="27" /> <!-- Ancient Gargoyle -->
		<npc id="21020" x="170196" y="37066" z="-4259" heading="39950" respawnDelay="27" /> <!-- Fallen Orc Shaman -->
		<npc id="20680" x="165756" y="38714" z="-3685" heading="14443" respawnDelay="27" /> <!-- Marsh Drake -->
		<npc id="21017" x="165843" y="39516" z="-3687" heading="12386" respawnDelay="27" /> <!-- Fallen Orc -->
		<npc id="20679" x="164541" y="40392" z="-3603" heading="27762" respawnDelay="27" /> <!-- Marsh Stalker -->
		<npc id="20680" x="165722" y="40602" z="-3719" heading="60673" respawnDelay="27" /> <!-- Marsh Drake -->
		<npc id="20679" x="166149" y="39680" z="-3687" heading="57892" respawnDelay="27" /> <!-- Marsh Stalker -->
		<npc id="20680" x="164861" y="39566" z="-3682" heading="45345" respawnDelay="27" /> <!-- Marsh Drake -->
		<npc id="20680" x="163835" y="40031" z="-3402" heading="30103" respawnDelay="27" /> <!-- Marsh Drake -->
	</spawn>
</list>

=== leopm99/mobiuz/dist/game/data/spawns/Giran/DragonValley.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn zone="giran06_cave_01">
		<territory minZ="-3500" maxZ="-2500">
			<node x="79988" y="104495" />
			<node x="78777" y="105646" />
			<node x="78989" y="107200" />
			<node x="81543" y="106601" />
		</territory>
		<npc id="20242" count="1" respawnDelay="36" chaseRange="2500" /> <!-- Dustwind Gargoyle -->
		<npc id="20134" count="5" respawnDelay="22" chaseRange="2500" /> <!-- Cave Maiden -->
		<npc id="20246" count="5" respawnDelay="22" chaseRange="2500" /> <!-- Cave Keeper -->
		<npc id="18001" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Blood Queen -->
	</spawn>
	<spawn zone="giran06_cave_02">
		<territory minZ="-3500" maxZ="-2500">
			<node x="78039" y="104825" />
			<node x="78093" y="106342" />
			<node x="74032" y="106676" />
			<node x="73889" y="105509" />
			<node x="75463" y="104704" />
		</territory>
		<npc id="20239" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Cave Servant Captain -->
		<npc id="20238" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Cave Servant Warrior -->
		<npc id="20236" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Cave Servant -->
		<npc id="20235" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Shackle -->
		<npc id="20237" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Cave Servant Archer -->
	</spawn>
	<spawn zone="giran06_cave_03">
		<territory minZ="-3500" maxZ="-2000">
			<node x="78584" y="106115" />
			<node x="74450" y="106748" />
			<node x="75027" y="109423" />
			<node x="78477" y="108061" />
		</territory>
		<npc id="20146" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Headless Knight -->
		<npc id="20246" count="5" respawnDelay="22" chaseRange="2500" /> <!-- Cave Keeper -->
		<npc id="20240" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Royal Cave Servant -->
		<npc id="20134" count="5" respawnDelay="22" chaseRange="2500" /> <!-- Cave Maiden -->
		<npc id="20241" count="2" respawnDelay="36" chaseRange="2500" /> <!-- Hunter Gargoyle -->
	</spawn>
</list>
