=== leopm99/mobiuz/dist/game/data/xsd/spawns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="spawn" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="AIData" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence minOccurs="1" maxOccurs="1">
										<xs:element type="xs:nonNegativeInteger" name="aggroRange" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomAnimation" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:boolean" name="disableRandomWalk" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeX" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeY" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="fleeZ" minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="territory" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="banned_territory" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="node" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:int" name="x" use="required" />
														<xs:attribute type="xs:int" name="y" use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="shape" use="optional" />
									<xs:attribute type="xs:short" name="minZ" use="required" />
									<xs:attribute type="xs:short" name="maxZ" use="required" />
									<xs:attribute type="xs:int" name="rad" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="id" type="xs:positiveInteger" use="required" />
											<xs:attribute name="x" type="xs:integer" use="optional" />
											<xs:attribute name="y" type="xs:integer" use="optional" />
											<xs:attribute name="z" type="xs:integer" use="optional" />
											<xs:attribute name="heading" type="xs:integer" use="optional" />
											<xs:attribute name="count" type="xs:positiveInteger" use="optional" />
											<xs:attribute name="respawnDelay" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="respawnRandom" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="chaseRange" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="randomWalkRange" type="xs:nonNegativeInteger" use="optional" />
											<xs:attribute name="periodOfDay" use="optional">
												<xs:simpleType>
													<xs:restriction base="xs:token">
														<xs:enumeration value="day" />
														<xs:enumeration value="night" />
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" use="optional" />
						<xs:attribute type="xs:string" name="zone" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required" />
	</xs:complexType>
	</xs:element>
</xs:schema>

=== leopm99/mobiuz/dist/game/data/spawns/Innadril/AlligatorBeach.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn zone="innadril13_2324_tas01">
		<territory minZ="-3753" maxZ="-2953">
			<node x="104812" y="201853" />
			<node x="106386" y="201898" />
			<node x="106134" y="204477" />
			<node x="103123" y="203007" />
		</territory>
		<npc id="20784" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="21639" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="20785" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21640" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21642" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
		<npc id="21643" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
	</spawn>
	<spawn zone="innadril13_2324_tas02">
		<territory minZ="-3784" maxZ="-3584">
			<node x="100663" y="199952" />
			<node x="102840" y="199311" />
			<node x="102618" y="200631" />
			<node x="100890" y="201048" />
		</territory>
		<npc id="20784" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="21639" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="20785" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21640" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21642" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
		<npc id="21643" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
	</spawn>
	<spawn zone="innadril13_2324_tas03">
		<territory minZ="-3092" maxZ="-2492">
			<node x="102952" y="209827" />
			<node x="104702" y="209799" />
			<node x="105958" y="211507" />
			<node x="105550" y="213106" />
		</territory>
		<npc id="20784" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="21639" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman -->
		<npc id="20785" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21640" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Tasaba Lizardman Shaman -->
		<npc id="21642" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
		<npc id="21643" count="1" respawnDelay="60" respawnRandom="30" /> <!-- Tasaba Lizardman Sniper -->
	</spawn>
	<spawn zone="innadril13_2324_croc01">
		<territory minZ="-3814" maxZ="-3014">
			<node x="109022" y="198572" />
			<node x="111677" y="199916" />
			<node x="109883" y="201624" />
			<node x="106772" y="201334" />
		</territory>
		<npc id="20135" count="3" respawnDelay="40" respawnRandom="20" /> <!-- Alligator -->
		<npc id="20792" count="3" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20791" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian Warrior -->
	</spawn>
	<spawn zone="innadril13_2324_croc02">
		<territory minZ="-3760" maxZ="-3460">
			<node x="108889" y="197996" />
			<node x="112323" y="199201" />
			<node x="111731" y="199822" />
			<node x="108634" y="198284" />
		</territory>
		<npc id="20135" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Alligator -->
		<npc id="20792" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20790" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Dailaon -->
	</spawn>
	<spawn zone="innadril13_2324_croc03">
		<territory minZ="-3814" maxZ="-3014">
			<node x="112870" y="198916" />
			<node x="113997" y="199265" />
			<node x="112526" y="201064" />
			<node x="110681" y="200917" />
		</territory>
		<npc id="20135" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Alligator -->
		<npc id="20792" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
	</spawn>
	<spawn zone="innadril13_2324_croc04">
		<territory minZ="-3804" maxZ="-3604">
			<node x="114020" y="199395" />
			<node x="115703" y="199157" />
			<node x="115836" y="199572" />
			<node x="113577" y="199902" />
		</territory>
		<npc id="20135" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Alligator -->
		<npc id="20792" count="1" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20790" count="1" respawnDelay="40" respawnRandom="20" /> <!-- Dailaon -->
	</spawn>
	<spawn zone="innadril13_2324_croc05">
		<territory minZ="-3819" maxZ="-3019">
			<node x="113733" y="200706" />
			<node x="116145" y="200194" />
			<node x="115379" y="202202" />
			<node x="112944" y="202817" />
		</territory>
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20790" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Dailaon -->
		<npc id="20791" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian Warrior -->
		<npc id="20793" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Nos -->
	</spawn>
	<spawn zone="innadril13_2324_croc06">
		<territory minZ="-3764" maxZ="-3564">
			<node x="117138" y="198615" />
			<node x="118016" y="198989" />
			<node x="118183" y="199896" />
			<node x="116519" y="199179" />
		</territory>
		<npc id="20792" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20790" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Dailaon -->
		<npc id="20791" count="1" respawnDelay="40" respawnRandom="20" /> <!-- Crokian Warrior -->
		<npc id="20793" count="1" respawnDelay="40" respawnRandom="20" /> <!-- Nos -->
	</spawn>
	<spawn zone="innadril13_2324_croc07">
		<territory minZ="-2896" maxZ="-2496">
			<node x="123819" y="200826" />
			<node x="125842" y="200991" />
			<node x="126187" y="201710" />
			<node x="124150" y="201856" />
		</territory>
		<npc id="20792" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Farhite -->
		<npc id="20789" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian -->
		<npc id="20790" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Dailaon -->
		<npc id="20791" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Crokian Warrior -->
		<npc id="20793" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Nos -->
	</spawn>
	<spawn zone="innadril13_2324_lien01">
		<territory minZ="-3816" maxZ="-3016">
			<node x="117679" y="211677" />
			<node x="121408" y="208460" />
			<node x="123515" y="208312" />
			<node x="122186" y="210758" />
			<node x="118246" y="212386" />
		</territory>
		<npc id="20786" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="21644" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="20787" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
		<npc id="21645" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
	</spawn>
	<spawn zone="innadril13_2324_lien02">
		<territory minZ="-3716" maxZ="-3316">
			<node x="120905" y="213536" />
			<node x="125560" y="213540" />
			<node x="124086" y="214957" />
			<node x="120317" y="215065" />
		</territory>
		<npc id="20786" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="21644" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="20787" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
		<npc id="21645" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
	</spawn>
	<spawn zone="innadril13_2324_lien03">
		<territory minZ="-3528" maxZ="-2928">
			<node x="123997" y="218677" />
			<node x="126409" y="218588" />
			<node x="126114" y="220819" />
			<node x="123804" y="219959" />
		</territory>
		<npc id="20786" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="21644" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="20787" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
		<npc id="21645" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
	</spawn>
	<spawn zone="innadril13_2324_lien04">
		<territory minZ="-2888" maxZ="-2388">
			<node x="122913" y="221694" />
			<node x="124357" y="221694" />
			<node x="124464" y="223751" />
			<node x="122750" y="223968" />
		</territory>
		<npc id="20786" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="21644" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik -->
		<npc id="20787" count="4" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
		<npc id="21645" count="2" respawnDelay="40" respawnRandom="20" /> <!-- Lienrik Lad -->
	</spawn>
	<spawn zone="innadril01_qm2324_01">
		<territory minZ="-4236" maxZ="-4036">
			<node x="106252" y="197068" />
			<node x="106452" y="197068" />
			<node x="106452" y="197268" />
			<node x="106252" y="197268" />
		</territory>
		<npc id="20314" count="3" respawnDelay="180" /> <!-- Great White Shark -->
	</spawn>
</list>

=== leopm99/mobiuz/dist/game/data/spawns/Aden/TheForbiddenGateway.xml
<?xml version="1.0" encoding="UTF-8"?>
<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn zone="aden06_2518_05">
		<territory minZ="-2776" maxZ="-2576">
			<node x="177724" y="5656" />
			<node x="178808" y="5660" />
			<node x="179312" y="6968" />
			<node x="179308" y="8836" />
			<node x="179056" y="9048" />
			<node x="177344" y="9044" />
			<node x="177356" y="6112" />
		</territory>
		<npc id="18001" count="2" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="1" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="2" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_06">
		<territory minZ="-2776" maxZ="-2576">
			<node x="180192" y="5712" />
			<node x="181252" y="5704" />
			<node x="181676" y="6208" />
			<node x="181632" y="9020" />
			<node x="179936" y="9036" />
			<node x="179692" y="8768" />
			<node x="179720" y="6960" />
		</territory>
		<npc id="20672" count="1" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_07">
		<territory minZ="-2768" maxZ="-2468">
			<node x="177408" y="9460" />
			<node x="179068" y="9460" />
			<node x="179316" y="9704" />
			<node x="179308" y="11776" />
			<node x="178648" y="12892" />
			<node x="177748" y="12888" />
			<node x="177360" y="12432" />
		</territory>
		<npc id="18001" count="2" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="2" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="1" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_36">
		<territory minZ="-2848" maxZ="-2448">
			<node x="182952" y="9880" />
			<node x="185436" y="9756" />
			<node x="187700" y="11588" />
			<node x="186668" y="13256" />
			<node x="183100" y="13004" />
		</territory>
		<npc id="18001" count="4" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" count="5" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" count="5" respawnDelay="25" /> <!-- Kadios -->
	</spawn>
	<spawn zone="aden06_2518_37">
		<territory minZ="-2808" maxZ="-2408">
			<node x="185944" y="7792" />
			<node x="187400" y="6096" />
			<node x="189028" y="8556" />
			<node x="189152" y="11116" />
			<node x="186288" y="9964" />
		</territory>
		<npc id="20672" count="4" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="5" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="4" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_38">
		<territory minZ="-2796" maxZ="-2396">
			<node x="181572" y="4164" />
			<node x="184760" y="4872" />
			<node x="186044" y="6308" />
			<node x="184864" y="9172" />
			<node x="182684" y="9200" />
		</territory>
		<npc id="20672" count="5" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="5" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="5" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_46">
		<territory minZ="-3732" maxZ="-3532">
			<node x="188004" y="24516" />
			<node x="191724" y="22848" />
			<node x="193000" y="23412" />
			<node x="188156" y="25572" />
		</territory>
		<npc id="20672" count="2" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="aden06_2518_47">
		<territory minZ="-3720" maxZ="-3520">
			<node x="190956" y="17436" />
			<node x="191992" y="16712" />
			<node x="193592" y="21832" />
			<node x="192348" y="21248" />
		</territory>
		<npc id="20672" count="2" respawnDelay="25" /> <!-- Trives -->
		<npc id="20673" count="2" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" count="2" respawnDelay="25" /> <!-- Doom Knight -->
	</spawn>
	<spawn zone="theForbiddenGateway">
		<npc id="20673" x="190445" y="17120" z="-3757" heading="6649" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20673" x="189136" y="18202" z="-3726" heading="50584" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20672" x="189082" y="18626" z="-3702" heading="17705" respawnDelay="25" /> <!-- Trives -->
		<npc id="20674" x="190587" y="19639" z="-3752" heading="4737" respawnDelay="25" /> <!-- Doom Knight -->
		<npc id="20673" x="191062" y="20085" z="-3752" heading="7754" respawnDelay="25" /> <!-- Falibati -->
		<npc id="20674" x="190036" y="18028" z="-3765" heading="40066" respawnDelay="25" /> <!-- Doom Knight -->
		<npc id="20674" x="188810" y="19034" z="-3728" heading="12350" respawnDelay="25" /> <!-- Doom Knight -->
		<npc id="18001" x="185949" y="18870" z="-3354" heading="31900" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" x="185121" y="17408" z="-3324" heading="34826" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="18001" x="185507" y="16937" z="-3313" heading="49886" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" x="185535" y="16202" z="-3318" heading="49549" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="18001" x="185349" y="15337" z="-3300" heading="51374" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20671" x="184969" y="15658" z="-3318" heading="19255" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20670" x="184356" y="14970" z="-3324" heading="32467" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20672" x="189690" y="22455" z="-3752" heading="52752" respawnDelay="25" /> <!-- Trives -->
		<npc id="18001" x="185334" y="22419" z="-3341" heading="43032" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" x="185489" y="21647" z="-3356" heading="45591" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" x="186039" y="21757" z="-3351" heading="60027" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20671" x="185270" y="22933" z="-3335" heading="19427" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20670" x="185813" y="25102" z="-3348" heading="10623" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="18001" x="185078" y="24221" z="-3338" heading="20172" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20671" x="185279" y="25095" z="-3315" heading="27542" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20670" x="184639" y="25707" z="-3338" heading="27419" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" x="186481" y="27892" z="-3675" heading="6186" respawnDelay="25" /> <!-- Kadios -->
		<npc id="18001" x="187258" y="27806" z="-3688" heading="58486" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20670" x="186590" y="28628" z="-3705" heading="22543" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="20671" x="184911" y="29599" z="-3726" heading="21097" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20671" x="183195" y="28405" z="-3722" heading="61098" respawnDelay="25" /> <!-- Kadios -->
		<npc id="20670" x="182104" y="28088" z="-3688" heading="35682" respawnDelay="25" /> <!-- Crimson Drake -->
		<npc id="18001" x="183780" y="28611" z="-3730" heading="17709" respawnDelay="25" /> <!-- Blood Queen -->
		<npc id="20672" x="188468" y="23228" z="-3723" heading="5963" respawnDelay="60" /> <!-- Trives -->
		<npc id="20674" x="188818" y="22638" z="-3732" heading="53669" respawnDelay="60" /> <!-- Doom Knight -->
		<npc id="20674" x="189656" y="21293" z="-3696" heading="52949" respawnDelay="60" /> <!-- Doom Knight -->
		<npc id="20674" x="191150" y="21456" z="-3696" heading="62928" respawnDelay="60" /> <!-- Doom Knight -->
		<npc id="20674" x="189859" y="23085" z="-3752" heading="28580" respawnDelay="60" /> <!-- Doom Knight -->
		<npc id="20673" x="189034" y="22937" z="-3731" heading="32916" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20673" x="188451" y="23206" z="-3722" heading="7091" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20673" x="190392" y="21792" z="-3696" heading="55207" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20673" x="191673" y="22134" z="-3696" heading="2721" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20672" x="190300" y="21117" z="-3696" heading="40028" respawnDelay="60" /> <!-- Trives -->
		<npc id="20672" x="191132" y="21787" z="-3696" heading="7071" respawnDelay="60" /> <!-- Trives -->
		<npc id="20672" x="190000" y="18727" z="-3753" heading="59266" respawnDelay="60" /> <!-- Trives -->
		<npc id="20673" x="189832" y="19277" z="-3745" heading="19476" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20673" x="191574" y="18154" z="-3694" heading="62020" respawnDelay="60" /> <!-- Falibati -->
		<npc id="20671" x="185359" y="17390" z="-3326" heading="18428" respawnDelay="60" /> <!-- Kadios -->
	</spawn>
</list>
